ubuntu-version: 14.04

language: php
php:
  - '5.3'
before_script:
  - sudo apt-get install enchant php5-enchant subversion libenchant-dev
  - svn checkout http://svn.php.net/repository/pecl/enchant/trunk enchant
  - cd enchant
  - phpize
  - ./configure
  - make
  - make install
  - echo "extension=enchant.so" > enchant.ini && phpenv config-add enchant.ini
  - cd ..
script:
  - php enchant.php
